### ISSUE TITLE
Wrong GVP and GVN responses

### ISSUE THREAD

**Issue by polakovic** [mappite/aGotino#5] opened 2021-02-19 08:08 UTC
Responses are not ended with '#' and thus protocol dialect detection is not possible.

**Comment by eliboni** [comment] 2021-02-19 18:13
Peter many thanks for the finding, you're right the final # is missed but it is required as per protocol specs. We'll fix it soon.

**Comment by eliboni** [comment] 2021-02-20 15:36
Fixed in main

**Closed by eliboni** 2021-02-20 15:36 UTC
Labels: bug

**Comment by eliboni** [comment] 2021-07-17 14:26
@polakovic the issue is closed since some time but pls if you can confirm it is solved  I would appreciate. Thanks

**Comment by polakovic** [comment] 2021-07-17 17:44
Unfortunately I don't have such mount so I can't confirm it :(
